include: package:very_good_analysis/analysis_options.yaml

formatter:
  trailing_commas: automate

linter:
  rules:
    avoid_print: false
    flutter_style_todos: false
    require_trailing_commas: false
